import { describe, it, expect } from 'vitest';
import {
  findActiveBlockAtLine,
  findCommentedBlockAtLine,
  parseImageLink,
  formatCommentedBlock,
  findMermaidBlockAtLine
} from '../markdown-parser';

describe('Markdown Parser', () => {
  describe('parseImageLink', () => {
    it('should parse wiki-style image links correctly', () => {
      const match = parseImageLink('![[attachments/mermaid-123.png]]');
      expect(match).not.toBeNull();
      expect(match!.path).toBe('attachments/mermaid-123.png');
      expect(match!.isRemote).toBe(false);
    });

    it('should parse wiki-style image links with alt or width text', () => {
      const match = parseImageLink('![[mermaid-123.png|300]]');
      expect(match).not.toBeNull();
      expect(match!.path).toBe('mermaid-123.png');
      expect(match!.isRemote).toBe(false);
    });

    it('should parse standard markdown image links correctly', () => {
      const match = parseImageLink('![alt text](images/diagram.png)');
      expect(match).not.toBeNull();
      expect(match!.path).toBe('images/diagram.png');
      expect(match!.isRemote).toBe(false);
    });

    it('should identify remote URLs as remote', () => {
      const match = parseImageLink('![](https://cdn.example.com/diagram.png)');
      expect(match).not.toBeNull();
      expect(match!.path).toBe('https://cdn.example.com/diagram.png');
      expect(match!.isRemote).toBe(true);
    });

    it('should return null for non-image links', () => {
      expect(parseImageLink('[Link](image.png)')).toBeNull();
      expect(parseImageLink('![[document.pdf]]')).not.toBeNull(); // PDF is also an embed, but let's see. In our case it parses it.
      expect(parseImageLink('plain text')).toBeNull();
    });
  });

  describe('findActiveBlockAtLine', () => {
    it('should find active block when cursor is on the opening tag', () => {
      const lines = [
        '# Note Title',
        '```mermaid',
        'graph TD',
        '  A --> B',
        '```',
        'some text'
      ];
      const block = findActiveBlockAtLine(lines, 1);
      expect(block).not.toBeNull();
      expect(block!.type).toBe('active');
      expect(block!.startLine).toBe(1);
      expect(block!.endLine).toBe(4);
      expect(block!.code).toBe('graph TD\n  A --> B');
    });

    it('should find active block when cursor is inside the code block', () => {
      const lines = [
        '# Note Title',
        '```mermaid',
        'graph TD',
        '  A --> B',
        '```',
        'some text'
      ];
      const block = findActiveBlockAtLine(lines, 2);
      expect(block).not.toBeNull();
      expect(block!.code).toBe('graph TD\n  A --> B');
    });

    it('should find active block when cursor is on the closing tag', () => {
      const lines = [
        '# Note Title',
        '```mermaid',
        'graph TD',
        '  A --> B',
        '```',
        'some text'
      ];
      const block = findActiveBlockAtLine(lines, 4);
      expect(block).not.toBeNull();
      expect(block!.startLine).toBe(1);
      expect(block!.endLine).toBe(4);
    });

    it('should return null if cursor is outside any code block', () => {
      const lines = [
        '# Note Title',
        '```mermaid',
        'graph TD',
        '  A --> B',
        '```',
        'some text'
      ];
      expect(findActiveBlockAtLine(lines, 0)).toBeNull();
      expect(findActiveBlockAtLine(lines, 5)).toBeNull();
    });

    it('should detect an existing image link immediately following the active block', () => {
      const lines = [
        '```mermaid',
        'graph TD',
        '  A --> B',
        '```',
        '![[mermaid-123.png]]'
      ];
      const block = findActiveBlockAtLine(lines, 1);
      expect(block).not.toBeNull();
      expect(block!.existingImageLink).toBe('![[mermaid-123.png]]');
      expect(block!.existingImagePath).toBe('mermaid-123.png');
      expect(block!.imageLinkLine).toBe(4);
    });
  });

  describe('findCommentedBlockAtLine', () => {
    const commentedBlockLines = [
      '# Document Title',
      '%% [Autogenerated by Mermaid Block to Image. Do not delete or modify this block]',
      '```mermaid',
      'graph TD',
      '  A --> B',
      '```',
      '%%',
      '![[attachments/mermaid-abc.png]]',
      'other normal content'
    ];

    it('should find commented block when cursor is on warning line', () => {
      const block = findCommentedBlockAtLine(commentedBlockLines, 1);
      expect(block).not.toBeNull();
      expect(block!.type).toBe('commented');
      expect(block!.startLine).toBe(1);
      expect(block!.endLine).toBe(6);
      expect(block!.code).toBe('graph TD\n  A --> B');
      expect(block!.existingImageLink).toBe('![[attachments/mermaid-abc.png]]');
      expect(block!.existingImagePath).toBe('attachments/mermaid-abc.png');
      expect(block!.imageLinkLine).toBe(7);
    });

    it('should find commented block when cursor is inside the code block', () => {
      const block = findCommentedBlockAtLine(commentedBlockLines, 3);
      expect(block).not.toBeNull();
      expect(block!.code).toBe('graph TD\n  A --> B');
    });

    it('should find commented block when cursor is on the image link line below it', () => {
      const block = findCommentedBlockAtLine(commentedBlockLines, 7);
      expect(block).not.toBeNull();
      expect(block!.type).toBe('commented');
      expect(block!.code).toBe('graph TD\n  A --> B');
    });

    it('should return null if cursor is completely outside the commented block range', () => {
      expect(findCommentedBlockAtLine(commentedBlockLines, 0)).toBeNull();
      expect(findCommentedBlockAtLine(commentedBlockLines, 8)).toBeNull();
    });
  });

  describe('findMermaidBlockAtLine unified helper', () => {
    it('should prioritize commented blocks over active blocks if inside both somehow, or detect active', () => {
      const lines = [
        '```mermaid',
        'graph TD',
        '```'
      ];
      const block = findMermaidBlockAtLine(lines, 1);
      expect(block).not.toBeNull();
      expect(block!.type).toBe('active');
    });
  });

  describe('formatCommentedBlock', () => {
    it('should output the warning line, code block, closing %%, and image link correctly', () => {
      const code = 'graph TD\n  A --> B';
      const imgLink = '![[mermaid-abc.png]]';
      const result = formatCommentedBlock(code, imgLink);

      const expected = [
        '%% [Autogenerated by Mermaid Block to Image. Do not delete or modify this block]',
        '```mermaid',
        'graph TD',
        '  A --> B',
        '```',
        '%%',
        '![[mermaid-abc.png]]'
      ].join('\n');

      expect(result).toBe(expected);
    });
  });
});
