/**
 * Structure describing a detected Mermaid diagram block.
 */
export interface MermaidBlock {
  /**
   * Type of detected block:
   * - 'active': A normal raw mermaid code block in markdown ( ```mermaid ... ``` ).
   * - 'commented': A mermaid code block already processed and commented out by the plugin.
   */
  type: 'active' | 'commented';
  /**
   * Start line index of the complete block in the document (0-based, inclusive).
   */
  startLine: number;
  /**
   * End line index of the complete block in the document (0-based, inclusive).
   * Note: In commented blocks, this is the line containing the closing '%%'.
   */
  endLine: number;
  /**
   * The extracted Mermaid diagram source code (excluding the triple backticks).
   */
  code: string;
  /**
   * The complete image link if an associated image was detected directly below the block.
   * E.g.: '![[mermaid-1a2b3c4d.png]]' or '![alt](mermaid-1a2b3c4d.png)'
   */
  existingImageLink?: string;
  /**
   * The extracted image file path or name parsed from existingImageLink.
   * E.g.: 'attachments/mermaid-1a2b3c4d.png'
   */
  existingImagePath?: string;
  /**
   * The exact line index where the associated image link was found (0-based).
   */
  imageLinkLine?: number;
}

/**
 * The autogenerated warning comment placed at the start of each commented code block.
 */
export const OPENING_WARNING = "%% [Autogenerated by Mermaid Block to Image Plugin. Do not delete or modify this line]";

/**
 * The autogenerated warning comment placed at the end of each commented code block.
 */
export const CLOSING_WARNING = "[Autogenerated by Mermaid Block to Image Plugin. Do not delete or modify this line] %%";

/**
 * Parses a markdown line to extract and decompose an image link
 * (supporting both Wikilink and standard Markdown image formats).
 * 
 * @param text The line of text to parse.
 * @returns An object containing the file path and whether it is a remote URL, or null if it does not match.
 */
export function parseImageLink(text: string): { path: string; isRemote: boolean } | null {
  const trimmed = text.trim();

  // 1. Detect Wikilink format: ![[file-path]] or ![[file-path|optional-alt-text]]
  const wikilinkRegex = /^!\[\[([^\]|]+)(?:\|[^\]]*)?\]\]$/;
  const wikiMatch = trimmed.match(wikilinkRegex);
  if (wikiMatch && wikiMatch[1]) {
    const path = wikiMatch[1].trim();
    return {
      path,
      isRemote: path.startsWith("http://") || path.startsWith("https://"),
    };
  }

  // 2. Detect standard Markdown image format: ![alt-text](file-path)
  const markdownRegex = /^!\[[^\]]*\]\(([^)]+)\)$/;
  const mdMatch = trimmed.match(markdownRegex);
  if (mdMatch && mdMatch[1]) {
    const path = mdMatch[1].trim();
    return {
      path,
      isRemote: path.startsWith("http://") || path.startsWith("https://"),
    };
  }

  return null;
}

/**
 * Finds an active (uncommented) Mermaid code block enclosing the specified line index (cursor).
 * 
 * @param lines Array of line strings from the document.
 * @param cursorLine The line index where the cursor is situated (0-based).
 * @returns The corresponding MermaidBlock object, or null if none is found at that line.
 */
export function findActiveBlockAtLine(lines: string[], cursorLine: number): MermaidBlock | null {
  if (cursorLine < 0 || cursorLine >= lines.length) return null;

  let startLine = -1;

  // Scan upwards to locate the code block start tag (```mermaid)
  for (let i = cursorLine; i >= 0; i--) {
    const line = lines[i]?.trim();
    if (line?.startsWith("```mermaid")) {
      startLine = i;
      break;
    } else if (line?.startsWith("```") && i !== cursorLine) {
      // Encountered the end of another code block before finding our start tag
      break;
    }
  }

  if (startLine === -1) return null;

  // Scan downwards to locate the closing tag (```)
  let endLine = -1;
  for (let i = startLine + 1; i < lines.length; i++) {
    const line = lines[i]?.trim();
    if (line?.startsWith("```")) {
      endLine = i;
      break;
    }
  }

  // If no closing tag is found or the cursor is beyond the block range
  if (endLine === -1 || cursorLine > endLine) {
    return null;
  }

  // Extract the diagram code
  const codeLines = lines.slice(startLine + 1, endLine);
  const code = codeLines.join("\n");

  // Scan up to 2 lines below the closing tag to check if an image link is already present
  let existingImageLink: string | undefined;
  let existingImagePath: string | undefined;
  let imageLinkLine: number | undefined;

  for (let offset = 1; offset <= 2; offset++) {
    const nextLineIdx = endLine + offset;
    if (nextLineIdx < lines.length) {
      const nextLine = lines[nextLineIdx] || "";
      const parsed = parseImageLink(nextLine);
      if (parsed) {
        existingImageLink = nextLine.trim();
        existingImagePath = parsed.path;
        imageLinkLine = nextLineIdx;
        break;
      }
    }
  }

  return {
    type: 'active',
    startLine,
    endLine,
    code,
    existingImageLink,
    existingImagePath,
    imageLinkLine,
  };
}

/**
 * Finds a commented-out Mermaid code block enclosing or relating to the specified line index (cursor).
 * Resolves the autogenerated warning comment block.
 * 
 * @param lines Array of line strings from the document.
 * @param cursorLine The line index where the cursor is situated (0-based).
 * @returns The corresponding MermaidBlock object, or null if none is found at that line.
 */
export function findCommentedBlockAtLine(lines: string[], cursorLine: number): MermaidBlock | null {
  if (cursorLine < 0 || cursorLine >= lines.length) return null;

  let startLine = -1;

  // Scan upwards to locate the autogenerated warning comment (our start marker)
  for (let i = cursorLine; i >= 0; i--) {
    const line = lines[i]?.trim();
    if (line === OPENING_WARNING) {
      const nextLine = lines[i + 1]?.trim() || "";
      if (nextLine.startsWith("```mermaid")) {
        startLine = i;
        break;
      }
    }
    // Stop if we cross another comment tag that is not ours
    if (i !== cursorLine && line?.startsWith("%%") && !line.includes("Autogenerated")) {
      break;
    }
  }

  // If the cursor is on the image link line right below the commented block,
  // the scan above might miss the block start by one index. Retry from cursorLine - 1.
  if (startLine === -1 && cursorLine > 0) {
    for (let i = cursorLine - 1; i >= 0; i--) {
      const line = lines[i]?.trim();
      if (line === OPENING_WARNING) {
        const nextLine = lines[i + 1]?.trim() || "";
        if (nextLine.startsWith("```mermaid")) {
          startLine = i;
          break;
        }
      }
      if (i !== cursorLine - 1 && line?.startsWith("%%") && !line.includes("Autogenerated")) {
        break;
      }
    }
  }

  if (startLine === -1) return null;

  // Validate the basic structure: the next line after the warning comment must be ```mermaid
  const nextLine = lines[startLine + 1]?.trim() || "";
  if (startLine + 1 >= lines.length || !nextLine.startsWith("```mermaid")) {
    return null;
  }

  // Scan downwards to locate the closing code tag (```)
  let codeEndLine = -1;
  for (let i = startLine + 2; i < lines.length; i++) {
    const line = lines[i]?.trim() || "";
    if (line.startsWith("```")) {
      codeEndLine = i;
      break;
    }
  }

  if (codeEndLine === -1) return null;

  // The next line after the code block must be the closing warning comment
  const commentEndLine = codeEndLine + 1;
  const commentEndText = lines[commentEndLine]?.trim() || "";
  if (commentEndLine >= lines.length || commentEndText !== CLOSING_WARNING) {
    return null;
  }

  // If the cursor is placed beyond the image line (commentEndLine + 1), it is outside the block
  if (cursorLine > commentEndLine + 1) {
    return null;
  }

  // Extract the diagram code from inside the commented block
  const codeLines = lines.slice(startLine + 2, codeEndLine);
  const code = codeLines.join("\n");

  // Locate the image link directly following the closing '%%' line
  let existingImageLink: string | undefined;
  let existingImagePath: string | undefined;
  let imageLinkLine: number | undefined;

  const potentialImgLine = commentEndLine + 1;
  if (potentialImgLine < lines.length) {
    const imgLineText = lines[potentialImgLine] || "";
    const parsed = parseImageLink(imgLineText);
    if (parsed) {
      existingImageLink = imgLineText.trim();
      existingImagePath = parsed.path;
      imageLinkLine = potentialImgLine;
    }
  }

  return {
    type: 'commented',
    startLine,
    endLine: commentEndLine,
    code,
    existingImageLink,
    existingImagePath,
    imageLinkLine,
  };
}

/**
 * Unified helper that checks for either commented-out or active Mermaid blocks 
 * at the specified cursor line index. Prioritizes commented blocks.
 * 
 * @param lines Array of line strings from the document.
 * @param cursorLine The line index where the cursor is situated (0-based).
 * @returns The corresponding MermaidBlock object, or null if none is found.
 */
export function findMermaidBlockAtLine(lines: string[], cursorLine: number): MermaidBlock | null {
  const commentedBlock = findCommentedBlockAtLine(lines, cursorLine);
  if (commentedBlock) return commentedBlock;

  return findActiveBlockAtLine(lines, cursorLine);
}

/**
 * Formats the final commented-out markdown block by wrapping the Mermaid code block,
 * prefixing the warning comment header, and placing the image link underneath.
 * 
 * @param mermaidCode The Mermaid diagram source code.
 * @param imageLink The formatted PNG image link, e.g. '![[mermaid-1a2b3c4d.png]]'
 * @returns The fully formatted markdown block.
 */
export function formatCommentedBlock(mermaidCode: string, imageLink: string): string {
  return [
    OPENING_WARNING,
    "```mermaid",
    mermaidCode,
    "```",
    CLOSING_WARNING,
    imageLink
  ].join("\n");
}

/**
 * Calculates a SHA-256 hash (8-character hex string) for a given text block.
 * 
 * @param code The diagram source code to process.
 * @returns A Promise resolving to the 8-character hex hash.
 */
export async function getCodeHash(code: string): Promise<string> {
  const encoder = new TextEncoder();
  const data = encoder.encode(code.trim());
  
  const hashBuffer = await crypto.subtle.digest("SHA-256", data);
  const hashArray = Array.from(new Uint8Array(hashBuffer));
  return hashArray
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("")
    .substring(0, 8);
}
