/**
 * Structure describing a detected Mermaid diagram block.
 */
export interface MermaidBlock {
  /**
   * Type of detected block:
   * - 'active': A normal raw mermaid code block in markdown ( ```mermaid ... ``` ).
   * - 'commented': A mermaid code block already processed and commented out by the plugin.
   */
  type: 'active' | 'commented';
  /**
   * Start line index of the complete block in the document (0-based, inclusive).
   */
  startLine: number;
  /**
   * End line index of the complete block in the document (0-based, inclusive).
   * Note: In commented blocks, this is the line containing the closing '%%'.
   */
  endLine: number;
  /**
   * The extracted Mermaid diagram source code (excluding the triple backticks).
   */
  code: string;
  /**
   * The complete image link if an associated image was detected directly below the block.
   * E.g.: '![[mermaid-1a2b3c4d.png]]' or '![alt](mermaid-1a2b3c4d.png)'
   */
  existingImageLink?: string;
  /**
   * The extracted image file path or name parsed from existingImageLink.
   * E.g.: 'attachments/mermaid-1a2b3c4d.png'
   */
  existingImagePath?: string;
  /**
   * The exact line index where the associated image link was found (0-based).
   */
  imageLinkLine?: number;
  /**
   * Whether the existing image is a remote URL link (e.g. hosted on a CDN).
   */
  isExistingImageRemote?: boolean;
}

/**
 * The autogenerated warning comment placed at the start of each commented code block.
 */
export const OPENING_WARNING = "%% [Autogenerated by Mermaid Block to Image Plugin. Do not delete or modify this line]";

/**
 * The autogenerated warning comment placed at the end of each commented code block.
 */
export const CLOSING_WARNING = "[Autogenerated by Mermaid Block to Image Plugin. Do not delete or modify this line] %%";

/**
 * Parses a markdown line to extract and decompose an image link
 * (supporting both Wikilink and standard Markdown image formats).
 * 
 * @param text The line of text to parse.
 * @returns An object containing the file path and whether it is a remote URL, or null if it does not match.
 */
export function parseImageLink(text: string): { path: string; isRemote: boolean; isCommented?: boolean } | null {
  const trimmed = text.trim();

  // Strip optional leading/trailing comments %% ... %%
  let content = trimmed;
  let isCommented = false;
  if (trimmed.startsWith("%%") && trimmed.endsWith("%%")) {
    content = trimmed.substring(2, trimmed.length - 2).trim();
    isCommented = true;
  }

  // 1. Detect Wikilink format: ![[file-path]] or ![[file-path|optional-alt-text]]
  const wikilinkRegex = /^!\[\[([^\]|]+)(?:\|[^\]]*)?\]\]$/;
  const wikiMatch = content.match(wikilinkRegex);
  if (wikiMatch && wikiMatch[1]) {
    const path = wikiMatch[1].trim();
    return {
      path,
      isRemote: path.startsWith("http://") || path.startsWith("https://") || path.startsWith("data:"),
      isCommented,
    };
  }

  // 2. Detect standard Markdown image format: ![alt-text](file-path)
  const markdownRegex = /^!\[[^\]]*\]\(([^)]+)\)$/;
  const mdMatch = content.match(markdownRegex);
  if (mdMatch && mdMatch[1]) {
    const path = mdMatch[1].trim();
    return {
      path,
      isRemote: path.startsWith("http://") || path.startsWith("https://") || path.startsWith("data:"),
      isCommented,
    };
  }

  return null;
}

/**
 * Finds an active (uncommented) Mermaid code block enclosing the specified line index (cursor).
 * 
 * @param lines Array of line strings from the document.
 * @param cursorLine The line index where the cursor is situated (0-based).
 * @returns The corresponding MermaidBlock object, or null if none is found at that line.
 */
export function findActiveBlockAtLine(lines: string[], cursorLine: number): MermaidBlock | null {
  if (cursorLine < 0 || cursorLine >= lines.length) return null;

  let startLine = -1;

  // Scan upwards to locate the code block start tag (```mermaid)
  for (let i = cursorLine; i >= 0; i--) {
    const line = lines[i]?.trim();
    if (line?.startsWith("```mermaid")) {
      startLine = i;
      break;
    } else if (line?.startsWith("```") && i !== cursorLine) {
      // Encountered the end of another code block before finding our start tag
      break;
    }
  }

  if (startLine === -1) return null;

  // Scan downwards to locate the closing tag (```)
  let endLine = -1;
  for (let i = startLine + 1; i < lines.length; i++) {
    const line = lines[i]?.trim();
    if (line?.startsWith("```")) {
      endLine = i;
      break;
    }
  }

  // If no closing tag is found or the cursor is beyond the block range
  if (endLine === -1 || cursorLine > endLine) {
    return null;
  }

  // Extract the diagram code
  const codeLines = lines.slice(startLine + 1, endLine);
  const code = codeLines.join("\n");

  // Scan up to 2 lines below the closing tag to check if an image link is already present
  let existingImageLink: string | undefined;
  let existingImagePath: string | undefined;
  let imageLinkLine: number | undefined;
  let isExistingImageRemote = false;

  for (let offset = 1; offset <= 2; offset++) {
    const nextLineIdx = endLine + offset;
    if (nextLineIdx < lines.length) {
      const nextLine = lines[nextLineIdx] || "";
      const parsed = parseImageLink(nextLine);
      if (parsed) {
        existingImageLink = nextLine.trim();
        existingImagePath = parsed.path;
        imageLinkLine = nextLineIdx;
        isExistingImageRemote = parsed.isRemote;
        break;
      }
    }
  }

  return {
    type: 'active',
    startLine,
    endLine,
    code,
    existingImageLink,
    existingImagePath,
    imageLinkLine,
    isExistingImageRemote,
  };
}

/**
 * Finds a commented-out Mermaid code block enclosing or relating to the specified line index (cursor).
 * Resolves the autogenerated warning comment block.
 * 
 * @param lines Array of line strings from the document.
 * @param cursorLine The line index where the cursor is situated (0-based).
 * @returns The corresponding MermaidBlock object, or null if none is found at that line.
 */
export function findCommentedBlockAtLine(lines: string[], cursorLine: number): MermaidBlock | null {
  if (cursorLine < 0 || cursorLine >= lines.length) return null;

  let startLine = -1;

  // Scan upwards to locate the autogenerated warning comment (our start marker)
  for (let i = cursorLine; i >= 0; i--) {
    const line = lines[i]?.trim();
    if (line === OPENING_WARNING) {
      const nextLine = lines[i + 1]?.trim() || "";
      if (nextLine.startsWith("```mermaid")) {
        startLine = i;
        break;
      }
    }
    // Stop if we cross another comment tag that is not ours
    if (i !== cursorLine && line?.startsWith("%%") && !line.includes("Autogenerated")) {
      break;
    }
  }

  // If the cursor is on the image link line right below the commented block,
  // the scan above might miss the block start by one index. Retry from cursorLine - 1.
  if (startLine === -1 && cursorLine > 0) {
    for (let i = cursorLine - 1; i >= 0; i--) {
      const line = lines[i]?.trim();
      if (line === OPENING_WARNING) {
        const nextLine = lines[i + 1]?.trim() || "";
        if (nextLine.startsWith("```mermaid")) {
          startLine = i;
          break;
        }
      }
      if (i !== cursorLine - 1 && line?.startsWith("%%") && !line.includes("Autogenerated")) {
        break;
      }
    }
  }

  if (startLine === -1) return null;

  // Validate the basic structure: the next line after the warning comment must be ```mermaid
  const nextLine = lines[startLine + 1]?.trim() || "";
  if (startLine + 1 >= lines.length || !nextLine.startsWith("```mermaid")) {
    return null;
  }

  // Scan downwards to locate the closing code tag (```)
  let codeEndLine = -1;
  for (let i = startLine + 2; i < lines.length; i++) {
    const line = lines[i]?.trim() || "";
    if (line.startsWith("```")) {
      codeEndLine = i;
      break;
    }
  }

  if (codeEndLine === -1) return null;

  // The next line after the code block must be the closing warning comment
  const commentEndLine = codeEndLine + 1;
  const commentEndText = lines[commentEndLine]?.trim() || "";
  if (commentEndLine >= lines.length || commentEndText !== CLOSING_WARNING) {
    return null;
  }

  // If the cursor is placed beyond the image line (commentEndLine + 1), it is outside the block
  if (cursorLine > commentEndLine + 1) {
    return null;
  }

  // Extract the diagram code from inside the commented block
  const codeLines = lines.slice(startLine + 2, codeEndLine);
  const code = codeLines.join("\n");

  // Locate the image link directly following the closing '%%' line
  let existingImageLink: string | undefined;
  let existingImagePath: string | undefined;
  let imageLinkLine: number | undefined;
  let isExistingImageRemote = false;

  const potentialImgLine = commentEndLine + 1;
  if (potentialImgLine < lines.length) {
    const imgLineText = lines[potentialImgLine] || "";
    const parsed = parseImageLink(imgLineText);
    if (parsed) {
      existingImageLink = imgLineText.trim();
      existingImagePath = parsed.path;
      imageLinkLine = potentialImgLine;
      isExistingImageRemote = parsed.isRemote;
    }
  }

  return {
    type: 'commented',
    startLine,
    endLine: commentEndLine,
    code,
    existingImageLink,
    existingImagePath,
    imageLinkLine,
    isExistingImageRemote,
  };
}

/**
 * Unified helper that checks for either commented-out or active Mermaid blocks 
 * at the specified cursor line index. Prioritizes commented blocks.
 * 
 * @param lines Array of line strings from the document.
 * @param cursorLine The line index where the cursor is situated (0-based).
 * @returns The corresponding MermaidBlock object, or null if none is found.
 */
export function findMermaidBlockAtLine(lines: string[], cursorLine: number): MermaidBlock | null {
  const commentedBlock = findCommentedBlockAtLine(lines, cursorLine);
  if (commentedBlock) return commentedBlock;

  return findActiveBlockAtLine(lines, cursorLine);
}

/**
 * Formats the final commented-out markdown block by wrapping the Mermaid code block,
 * prefixing the warning comment header, and placing the image link underneath.
 * 
 * @param mermaidCode The Mermaid diagram source code.
 * @param imageLink The formatted PNG image link, e.g. '![[mermaid-1a2b3c4d.png]]'
 * @returns The fully formatted markdown block.
 */
export function formatCommentedBlock(mermaidCode: string, imageLink: string): string {
  return [
    OPENING_WARNING,
    "```mermaid",
    mermaidCode,
    "```",
    CLOSING_WARNING,
    imageLink
  ].join("\n");
}

/**
 * Calculates a SHA-256 hash (8-character hex string) for a given text block.
 * 
 * @param code The diagram source code to process.
 * @returns A Promise resolving to the 8-character hex hash.
 */
export async function getCodeHash(code: string): Promise<string> {
  const encoder = new TextEncoder();
  const data = encoder.encode(code.trim());
  
  const hashBuffer = await crypto.subtle.digest("SHA-256", data);
  const hashArray = Array.from(new Uint8Array(hashBuffer));
  return hashArray
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("")
    .substring(0, 8);
}

/**
 * Extracts a title from the Mermaid source code.
 * Standardizes on YAML-like frontmatter `title: ...` or diagram-specific `title ...` definitions.
 * 
 * @param code The diagram source code.
 * @returns The extracted title string, or null if none is found.
 */
export function extractTitle(code: string): string | null {
  const trimmedCode = code.trim();
  
  // 1. Parse frontmatter title:
  if (trimmedCode.startsWith("---")) {
    const parts = trimmedCode.split("---");
    if (parts.length >= 3) {
      const frontmatter = parts[1];
      if (frontmatter) {
        const titleMatch = frontmatter.match(/^\s*title\s*:\s*(.*)$/m);
        if (titleMatch && titleMatch[1]) {
          let title = titleMatch[1].trim();
          if (
            (title.startsWith('"') && title.endsWith('"')) ||
            (title.startsWith("'") && title.endsWith("'"))
          ) {
            title = title.substring(1, title.length - 1).trim();
          }
          if (title) return title;
        }
      }
    }
  }

  // 2. Parse inline/diagram-specific titles:
  const lines = code.split("\n");
  for (const line of lines) {
    const trimmedLine = line.trim();
    if (trimmedLine.startsWith("%%")) continue;
    
    const titleMatch = trimmedLine.match(/^title\s+(.+)$/i);
    if (titleMatch && titleMatch[1]) {
      let title = titleMatch[1].trim();
      if (
        (title.startsWith('"') && title.endsWith('"')) ||
        (title.startsWith("'") && title.endsWith("'"))
      ) {
        title = title.substring(1, title.length - 1).trim();
      }
      return title;
    }

    const pieMatch = trimmedLine.match(/^pie\s+title\s+(.+)$/i);
    if (pieMatch && pieMatch[1]) {
      let title = pieMatch[1].trim();
      if (
        (title.startsWith('"') && title.endsWith('"')) ||
        (title.startsWith("'") && title.endsWith("'"))
      ) {
        title = title.substring(1, title.length - 1).trim();
      }
      return title;
    }
  }

  return null;
}

/**
 * Converts a text title into a url-safe slug.
 * Removes accents, converts to lowercase, replaces non-alphanumeric characters with hyphens,
 * and trims leading/trailing hyphens.
 * 
 * @param text The input title string.
 * @returns A slugified string.
 */
export function slugify(text: string): string {
  return text
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

/**
 * Checks if the diagram source code already contains a custom theme configuration.
 * Specifically checks for:
 * 1. An init block with a theme definition (e.g. `%%{init: { 'theme': '...' }}%%`)
 * 2. A YAML frontmatter configuration containing a theme definition (e.g. `theme: forest`)
 * 
 * @param code The diagram source code.
 * @returns True if a custom theme configuration is detected in the code block.
 */
export function hasThemeInCode(code: string): boolean {
  if (/%%\s*\{\s*init\s*:.*theme\b/i.test(code)) {
    return true;
  }

  const trimmed = code.trim();
  if (trimmed.startsWith("---")) {
    const lines = code.split("\n");
    let openingIndex = -1;
    for (let i = 0; i < lines.length; i++) {
      if (lines[i]?.trim() === "---") {
        openingIndex = i;
        break;
      }
    }

    if (openingIndex !== -1) {
      let closingIndex = -1;
      for (let i = openingIndex + 1; i < lines.length; i++) {
        if (lines[i]?.trim() === "---") {
          closingIndex = i;
          break;
        }
      }

      if (closingIndex !== -1) {
        const frontmatterLines = lines.slice(openingIndex + 1, closingIndex);
        const frontmatterContent = frontmatterLines.join("\n");
        if (/\btheme\s*:/i.test(frontmatterContent)) {
          return true;
        }
      }
    }
  }

  return false;
}

/**
 * Injects a theme initialization directive into the Mermaid code block
 * if the block does not already contain an init block or a theme declaration.
 * Handles blocks starting with YAML frontmatter correctly by inserting
 * the directive after the closing frontmatter delimiter.
 * 
 * @param code The diagram source code.
 * @param theme The theme name to inject.
 * @returns The code with the theme directive injected if applicable.
 */
export function injectThemeDirective(code: string, theme: string): string {
  if (hasThemeInCode(code) || /%%\s*\{\s*init\s*:/i.test(code) || code.includes("%%{init:") || code.includes("%%{init}")) {
    return code;
  }

  const trimmed = code.trim();
  if (trimmed.startsWith("---")) {
    const lines = code.split("\n");
    let openingIndex = -1;
    for (let i = 0; i < lines.length; i++) {
      if (lines[i]?.trim() === "---") {
        openingIndex = i;
        break;
      }
    }

    if (openingIndex !== -1) {
      let closingIndex = -1;
      for (let i = openingIndex + 1; i < lines.length; i++) {
        if (lines[i]?.trim() === "---") {
          closingIndex = i;
          break;
        }
      }

      if (closingIndex !== -1) {
        const before = lines.slice(0, closingIndex + 1).join("\n");
        const after = lines.slice(closingIndex + 1).join("\n");
        return `${before}\n%%{init: {'theme': '${theme}'}}%%\n${after}`;
      }
    }
  }

  return `%%{init: {'theme': '${theme}'}}%%\n${code}`;
}

/**
 * Regex to detect and strip auto-injected theme directives on restore.
 */
export const INJECTED_THEME_REGEX = /(?:^|(\r?\n))%%\{init:\s*\{\s*['"]theme['"]\s*:\s*['"](?:default|dark|forest|neutral|base)['"]\s*\}\}%%\r?\n/i;

/**
 * Strips the auto-injected theme directive if present.
 * 
 * @param code The diagram source code.
 * @returns The diagram source code with the injected theme directive removed.
 */
export function stripInjectedTheme(code: string): string {
  return code.replace(INJECTED_THEME_REGEX, "$1");
}

