/**
 * Estructura que describe un bloque de diagrama Mermaid detectado.
 */
export interface MermaidBlock {
  /**
   * Tipo de bloque detectado:
   * - 'active': Un bloque de código mermaid normal en markdown ( ```mermaid ... ``` ).
   * - 'commented': Un bloque de código mermaid ya procesado y comentado por el plugin.
   */
  type: 'active' | 'commented';
  /**
   * Línea de inicio del bloque completo en el documento (0-based, inclusivo).
   */
  startLine: number;
  /**
   * Línea final del bloque completo en el documento (0-based, inclusivo).
   * Nota: En bloques comentados, esta es la línea con el '%%' de cierre del comentario.
   */
  endLine: number;
  /**
   * El código del diagrama Mermaid extraído (sin las triples comillas de inicio/cierre).
   */
  code: string;
  /**
   * El enlace de la imagen completo si se detectó una imagen asociada directamente debajo del bloque.
   * Ej: '![[mermaid-1a2b3c4d.png]]' o '![alt](mermaid-1a2b3c4d.png)'
   */
  existingImageLink?: string;
  /**
   * La ruta o nombre del archivo de imagen extraído a partir de existingImageLink.
   * Ej: 'attachments/mermaid-1a2b3c4d.png'
   */
  existingImagePath?: string;
  /**
   * La línea exacta donde se encuentra el enlace de la imagen asociada (0-based).
   */
  imageLinkLine?: number;
}

/**
 * El comentario de advertencia autogenerado que se coloca antes de cada bloque de código comentado.
 */
export const WARNING_COMMENT = "%% [Autogenerated by Mermaid Block to Image. Do not delete or modify this block]";

/**
 * Analiza una línea de texto de markdown para extraer y descomponer un enlace de imagen
 * (ya sea formato Wikilink o formato Markdown estándar).
 * 
 * @param text La línea de texto a analizar.
 * @returns Un objeto con la ruta del archivo y si es una URL remota, o null si no coincide.
 */
export function parseImageLink(text: string): { path: string; isRemote: boolean } | null {
  const trimmed = text.trim();

  // 1. Detectar formato Wikilink: ![[ruta-del-archivo]] o ![[ruta-del-archivo|texto-opcional]]
  const wikilinkRegex = /^!\[\[([^\]|]+)(?:\|[^\]]*)?\]\]$/;
  const wikiMatch = trimmed.match(wikilinkRegex);
  if (wikiMatch && wikiMatch[1]) {
    const path = wikiMatch[1].trim();
    return {
      path,
      isRemote: path.startsWith("http://") || path.startsWith("https://"),
    };
  }

  // 2. Detectar formato Markdown estándar: ![texto-alt](ruta-del-archivo)
  const markdownRegex = /^!\[[^\]]*\]\(([^)]+)\)$/;
  const mdMatch = trimmed.match(markdownRegex);
  if (mdMatch && mdMatch[1]) {
    const path = mdMatch[1].trim();
    return {
      path,
      isRemote: path.startsWith("http://") || path.startsWith("https://"),
    };
  }

  return null;
}

/**
 * Busca un bloque de código Mermaid activo (sin comentar) que contenga la línea especificada (cursor).
 * 
 * @param lines Array de líneas del documento de texto.
 * @param cursorLine El índice de línea donde está situado el cursor (0-based).
 * @returns El objeto MermaidBlock correspondiente, o null si no se encuentra en esa línea.
 */
export function findActiveBlockAtLine(lines: string[], cursorLine: number): MermaidBlock | null {
  if (cursorLine < 0 || cursorLine >= lines.length) return null;

  let startLine = -1;

  // Escanear hacia arriba para encontrar la apertura del bloque de código (```mermaid)
  for (let i = cursorLine; i >= 0; i--) {
    const line = lines[i]?.trim();
    if (line?.startsWith("```mermaid")) {
      startLine = i;
      break;
    } else if (line?.startsWith("```") && i !== cursorLine) {
      // Nos topamos con el cierre de otra sección de código antes del inicio del bloque esperado
      break;
    }
  }

  if (startLine === -1) return null;

  // Escanear hacia abajo para encontrar el cierre de código (```)
  let endLine = -1;
  for (let i = startLine + 1; i < lines.length; i++) {
    const line = lines[i]?.trim();
    if (line?.startsWith("```")) {
      endLine = i;
      break;
    }
  }

  // Si no se encuentra cierre, o el cursor está fuera del rango del bloque delimitado
  if (endLine === -1 || cursorLine > endLine) {
    return null;
  }

  // Extraer el código fuente del diagrama
  const codeLines = lines.slice(startLine + 1, endLine);
  const code = codeLines.join("\n");

  // Escanear hasta 2 líneas más abajo del cierre del bloque para detectar si ya hay una imagen asociada
  let existingImageLink: string | undefined;
  let existingImagePath: string | undefined;
  let imageLinkLine: number | undefined;

  for (let offset = 1; offset <= 2; offset++) {
    const nextLineIdx = endLine + offset;
    if (nextLineIdx < lines.length) {
      const nextLine = lines[nextLineIdx] || "";
      const parsed = parseImageLink(nextLine);
      if (parsed) {
        existingImageLink = nextLine.trim();
        existingImagePath = parsed.path;
        imageLinkLine = nextLineIdx;
        break;
      }
    }
  }

  return {
    type: 'active',
    startLine,
    endLine,
    code,
    existingImageLink,
    existingImagePath,
    imageLinkLine,
  };
}

/**
 * Busca un bloque de código Mermaid comentado (ya convertido) que contenga o se relacione 
 * con la línea especificada (cursor). Detecta el bloque de advertencia autogenerado.
 * 
 * @param lines Array de líneas del documento de texto.
 * @param cursorLine El índice de línea donde está situado el cursor (0-based).
 * @returns El objeto MermaidBlock correspondiente, o null si no se encuentra en esa línea.
 */
export function findCommentedBlockAtLine(lines: string[], cursorLine: number): MermaidBlock | null {
  if (cursorLine < 0 || cursorLine >= lines.length) return null;

  let startLine = -1;

  // Escanear hacia arriba para localizar la advertencia de autogeneración (nuestro marcador de inicio)
  for (let i = cursorLine; i >= 0; i--) {
    const line = lines[i]?.trim();
    if (line === WARNING_COMMENT) {
      startLine = i;
      break;
    }
    // Parar si cruzamos otro comentario nativo que no sea el nuestro
    if (i !== cursorLine && line?.startsWith("%%") && !line.includes("Autogenerated")) {
      break;
    }
  }

  // Si la línea del cursor es la imagen adjunta justo debajo del bloque comentado,
  // el escaneo hacia arriba anterior podría fallar por un índice. Intentar desde cursorLine - 1.
  if (startLine === -1 && cursorLine > 0) {
    for (let i = cursorLine - 1; i >= 0; i--) {
      const line = lines[i]?.trim();
      if (line === WARNING_COMMENT) {
        startLine = i;
        break;
      }
      if (i !== cursorLine - 1 && line?.startsWith("%%") && !line.includes("Autogenerated")) {
        break;
      }
    }
  }

  if (startLine === -1) return null;

  // Validar estructura básica: la siguiente línea después del comentario debe ser ```mermaid
  const nextLine = lines[startLine + 1]?.trim() || "";
  if (startLine + 1 >= lines.length || !nextLine.startsWith("```mermaid")) {
    return null;
  }

  // Escanear para encontrar el cierre del código ```
  let codeEndLine = -1;
  for (let i = startLine + 2; i < lines.length; i++) {
    const line = lines[i]?.trim() || "";
    if (line.startsWith("```")) {
      codeEndLine = i;
      break;
    }
  }

  if (codeEndLine === -1) return null;

  // La siguiente línea tras el cierre del código debe ser el %% de cierre del comentario
  const commentEndLine = codeEndLine + 1;
  const commentEndText = lines[commentEndLine]?.trim() || "";
  if (commentEndLine >= lines.length || commentEndText !== "%%") {
    return null;
  }

  // Si el cursor está más allá de la línea de la imagen (commentEndLine + 1), está fuera del bloque
  if (cursorLine > commentEndLine + 1) {
    return null;
  }

  // Extraer el código fuente del diagrama del bloque comentado
  const codeLines = lines.slice(startLine + 2, codeEndLine);
  const code = codeLines.join("\n");

  // Localizar el enlace de imagen asociado inmediatamente después de la línea %% de cierre
  let existingImageLink: string | undefined;
  let existingImagePath: string | undefined;
  let imageLinkLine: number | undefined;

  const potentialImgLine = commentEndLine + 1;
  if (potentialImgLine < lines.length) {
    const imgLineText = lines[potentialImgLine] || "";
    const parsed = parseImageLink(imgLineText);
    if (parsed) {
      existingImageLink = imgLineText.trim();
      existingImagePath = parsed.path;
      imageLinkLine = potentialImgLine;
    }
  }

  return {
    type: 'commented',
    startLine,
    endLine: commentEndLine,
    code,
    existingImageLink,
    existingImagePath,
    imageLinkLine,
  };
}

/**
 * Busca de forma unificada cualquier bloque Mermaid (activo o comentado) en la línea
 * del cursor indicada. Prioriza la detección de bloques comentados.
 * 
 * @param lines Array de líneas del documento de texto.
 * @param cursorLine El índice de línea donde está situado el cursor (0-based).
 * @returns El objeto MermaidBlock correspondiente, o null si no hay un bloque en esa línea.
 */
export function findMermaidBlockAtLine(lines: string[], cursorLine: number): MermaidBlock | null {
  // Intentar encontrar un bloque comentado primero
  const commentedBlock = findCommentedBlockAtLine(lines, cursorLine);
  if (commentedBlock) return commentedBlock;

  // Si no hay bloque comentado, intentar con uno activo normal
  return findActiveBlockAtLine(lines, cursorLine);
}

/**
 * Genera el formato final del bloque de comentarios de Obsidian envolviendo el código Mermaid,
 * agregando el mensaje de advertencia autogenerado y situando el enlace de imagen debajo.
 * 
 * @param mermaidCode El código fuente del diagrama Mermaid.
 * @param imageLink El enlace formateado de la imagen PNG, ej: '![[mermaid-1a2b3c4d.png]]'
 * @returns El bloque de texto formateado listo para insertarse en el documento.
 */
export function formatCommentedBlock(mermaidCode: string, imageLink: string): string {
  return [
    WARNING_COMMENT,
    "```mermaid",
    mermaidCode,
    "```",
    "%%",
    imageLink
  ].join("\n");
}
